### ISSUE TITLE
Cannot drop a runtime in a context

### ISSUE THREAD

**Issue by measproem** [spectare/actix-4-jwt-auth#11]
I am newbie
I followed [doc](https://docs.rs/actix-4-jwt-auth/0.4.2/actix_4_jwt_auth) when I run `cargo run` than I got error like below 
    `
    warning: `api` (bin "api") generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 9.19s
     Running `target/debug/api`
    thread 'main' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/blocking/shutdown.rs:51:21
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
   `

But when I run `cargo test` passed all.

I have update dependencies to latest version 

    [package]
    name = "api"
    version = "0.1.0"
    edition = "2021"

    [dependencies]
    actix-web = "4.1.0"
    actix-4-jwt-auth = "0.4.4"

    actix-rt = "2.7.0"
    actix-service = "2.0.2"
    biscuit = "0.6.0-beta1"
    bytes = "1.2.1"
    derive_more = "0.99.17"
    env_logger = "0.9.0"
    futures = "0.3.23"
    futures-core = {version = "0.3.23", default-features = false, features = ["alloc"]}
    futures-util = {version = "0.3.23", default-features = false, features = ["alloc"]}
    log = "0.4.17"
    reqwest = {version = "0.11.11", features = ["json", "blocking"]}
    sanitize-filename = "0.4"
    serde = {version = "1", features = ["derive"]}
    serde_derive = "1"
    serde_json = "1"
    thiserror = "1.0.32"
    tokio = {version = "1.20.1", features = ["full"]}

    [dev-dependencies]
    pretty_assertions= "1.2.1"

**Comment by olger** [comment]
Hi measproem, 

Nice to meet you. Without knowing your code, It maybe an issue that you use a async function outside a runtime context, best thing todo is to have a careful look at the functions you use for configuration outside the App::new

**Comment by measproem** [comment]
My main.rs file

    `use actix_4_jwt_auth::{AuthenticatedUser, OIDCValidator, OIDCValidatorConfig};
    use actix_web::{get, http::header, test, web, App, Error, HttpResponse, HttpServer};
    use serde::{Deserialize, Serialize};


    #[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]

    pub struct FoundClaims {
    
    pub iss: String,
    
    pub sub: String,
    
    pub aud: String,
    
    pub name: String,
    
    pub email: Option<String>,
    
    pub email_verified: Option<bool>,

    }
     

    #[get("/authenticated_user")]

    async fn authenticated_user(user: AuthenticatedUser<FoundClaims>) -> String {
    
    format!("Welcome {}!", user.claims.name)

    }


    #[actix_rt::main]

    async fn main() -> std::io::Result<()> {
    
    let test_issuer = "https://a.valid.openid-connect.idp/".to_string();
    
    let created_validator = OIDCValidator::new_from_issuer(test_issuer.clone()).unwrap();
    
    let validator_config = OIDCValidatorConfig {
        
    issuer: test_issuer,
        
    validator: created_validator,
    
    };
     
    
    HttpServer::new(move || {
      
    App::new()
    
              .app_data(validator_config.clone())
    
              .service(authenticated_user)
    
      })
    
    .bind("192.168.217.130:8081".to_string())?
    
    .run()
    
    .await

    }`

**Comment by dermicha** [comment]
Hey, I have same issue, here is my code:

`use actix_4_jwt_auth::{AuthenticatedUser, OIDCValidator, OIDCValidatorConfig};
use actix_web::{get, App, HttpServer};
use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
pub struct FoundClaims {
    pub iss: String,
    pub sub: String,
    pub aud: String,
    pub name: String,
    pub email: Option<String>,
    pub email_verified: Option<bool>,
}

#[get("/authenticated_user")]
async fn authenticated_user(user: AuthenticatedUser<FoundClaims>) -> String {
    format!("Welcome {}!", user.claims.name)
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    let test_issuer = "http://localhost:8080/auth/realms/test/".to_string();
    let created_validator = OIDCValidator::new_from_issuer(test_issuer.clone()).unwrap();
    let validator_config = OIDCValidatorConfig {
        issuer: test_issuer,
        validator: created_validator,
    };

    HttpServer::new(move || {
        App::new()
            .app_data(validator_config.clone())
            .service(authenticated_user)
    })
        .bind("0.0.0.0:8080".to_string())?
        .run()
        .await
}`

It is stupid simple test project, I just wanted to test keycloak integration.

Thanks for your help.

**Comment by dermicha** [comment]
this happens when starting it:

`RUST_BACKTRACE=1 cargo run                                                                                                                                                     101 ✘  4s  
   Compiling hello_actix_web v0.1.0 (/home/dermicha/workspace/rust/helloActixWeb)
    Finished dev [unoptimized + debuginfo] target(s) in 5.77s
     Running `target/debug/hello_actix_web`
thread 'main' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/blocking/shutdown.rs:51:21
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/801821d1560f84e4716fcbd9244ec959320a13d5/library/std/src/panicking.rs:616:12
   1: tokio::runtime::blocking::shutdown::Receiver::wait
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/blocking/shutdown.rs:51:21
   2: tokio::runtime::blocking::pool::BlockingPool::shutdown
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/blocking/pool.rs:193:12
   3: <tokio::runtime::blocking::pool::BlockingPool as core::ops::drop::Drop>::drop
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/blocking/pool.rs:210:9
   4: core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool>
             at /rustc/801821d1560f84e4716fcbd9244ec959320a13d5/library/core/src/ptr/mod.rs:487:1
   5: core::ptr::drop_in_place<tokio::runtime::Runtime>
             at /rustc/801821d1560f84e4716fcbd9244ec959320a13d5/library/core/src/ptr/mod.rs:487:1
   6: reqwest::blocking::wait::enter
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.11/src/blocking/wait.rs:76:21
   7: reqwest::blocking::wait::timeout
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.11/src/blocking/wait.rs:13:5
   8: reqwest::blocking::client::ClientHandle::new
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.11/src/blocking/client.rs:1010:15
   9: reqwest::blocking::client::ClientBuilder::build
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.11/src/blocking/client.rs:103:9
  10: reqwest::blocking::get
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.11/src/blocking/mod.rs:107:5
  11: actix_4_jwt_auth::OIDCValidator::fetch_discovery
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-4-jwt-auth-0.4.4/src/lib.rs:176:19
  12: actix_4_jwt_auth::OIDCValidator::new_from_issuer
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-4-jwt-auth-0.4.4/src/lib.rs:132:34
  13: hello_actix_web::main::{{closure}}
             at ./src/main.rs:23:29
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/801821d1560f84e4716fcbd9244ec959320a13d5/library/core/src/future/mod.rs:91:19
  15: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}::{{closure}}
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/task/local.rs:757:65
  16: tokio::coop::with_budget::{{closure}}
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:102:9
  17: std::thread::local::LocalKey<T>::try_with
             at /rustc/801821d1560f84e4716fcbd9244ec959320a13d5/library/std/src/thread/local.rs:445:16
  18: std::thread::local::LocalKey<T>::with
             at /rustc/801821d1560f84e4716fcbd9244ec959320a13d5/library/std/src/thread/local.rs:421:9
  19: tokio::coop::with_budget
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:95:5
  20: tokio::coop::budget
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:72:5
  21: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/task/local.rs:757:42
  22: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/macros/scoped_tls.rs:61:9
  23: tokio::task::local::LocalSet::with
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/task/local.rs:582:9
  24: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/task/local.rs:747:9
  25: tokio::task::local::LocalSet::run_until::{{closure}}
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/task/local.rs:502:18
  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/801821d1560f84e4716fcbd9244ec959320a13d5/library/core/src/future/mod.rs:91:19
  27: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/801821d1560f84e4716fcbd9244ec959320a13d5/library/core/src/future/future.rs:124:9
  28: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/basic_scheduler.rs:543:48
  29: tokio::coop::with_budget::{{closure}}
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:102:9
  30: std::thread::local::LocalKey<T>::try_with
             at /rustc/801821d1560f84e4716fcbd9244ec959320a13d5/library/std/src/thread/local.rs:445:16
  31: std::thread::local::LocalKey<T>::with
             at /rustc/801821d1560f84e4716fcbd9244ec959320a13d5/library/std/src/thread/local.rs:421:9
  32: tokio::coop::with_budget
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:95:5
  33: tokio::coop::budget
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:72:5
  34: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/basic_scheduler.rs:543:25
  35: tokio::runtime::basic_scheduler::Context::enter
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/basic_scheduler.rs:367:19
  36: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/basic_scheduler.rs:542:36
  37: tokio::runtime::basic_scheduler::CoreGuard::enter::{{closure}}
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/basic_scheduler.rs:613:57
  38: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/macros/scoped_tls.rs:61:9
  39: tokio::runtime::basic_scheduler::CoreGuard::enter
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/basic_scheduler.rs:613:27
  40: tokio::runtime::basic_scheduler::CoreGuard::block_on
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/basic_scheduler.rs:533:19
  41: tokio::runtime::basic_scheduler::BasicScheduler::block_on
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/basic_scheduler.rs:179:24
  42: tokio::runtime::Runtime::block_on
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/mod.rs:482:46
  43: tokio::task::local::LocalSet::block_on
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/task/local.rs:463:9
  44: actix_rt::runtime::Runtime::block_on
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-2.7.0/src/runtime.rs:80:9
  45: actix_rt::system::SystemRunner::block_on
             at /home/dermicha/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-2.7.0/src/system.rs:209:9
  46: hello_actix_web::main
             at ./src/main.rs:20:1
  47: core::ops::function::FnOnce::call_once
             at /rustc/801821d1560f84e4716fcbd9244ec959320a13d5/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
`

**Comment by olger** [comment]
I've checked and it is an issue with the use of reqwest (async http client) inside the new_from_issuer. 
I tried to hide the async part as you more or less always need to block the creation of the App config. This doesn't work (anymore). 

I'll do some research to see what a proper solution is for this combination.

**Comment by olger** [comment]
For now, you can solve the issue like this: (NOTE the task::spawn_blocking)

```rust
use actix_4_jwt_auth::{AuthenticatedUser, OIDCValidator, OIDCValidatorConfig};
use actix_web::{get, http::header, test, web, App, Error, HttpResponse, HttpServer};
use serde::{Deserialize, Serialize};
use tokio::task;

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]

pub struct FoundClaims {
    pub iss: String,

    pub sub: String,

    pub aud: String,

    pub name: String,

    pub email: Option<String>,

    pub email_verified: Option<bool>,
}

#[get("/authenticated_user")]

async fn authenticated_user(user: AuthenticatedUser<FoundClaims>) -> String {
    format!("Welcome {}!", user.claims.name)
}

#[actix_rt::main]
async fn main() -> std::io::Result<()> {
    let test_issuer = "https://accounts.google.com";
    let res = task::spawn_blocking(move || {
        OIDCValidator::new_from_issuer(test_issuer.to_string()).unwrap()
    }).await;

    let created_validator = res.expect("Cannot retrieve");

    let validator_config = OIDCValidatorConfig {
        issuer: test_issuer.to_string(),

        validator: created_validator,
    };

    HttpServer::new(move || {
        App::new()
            .app_data(validator_config.clone())
            .service(authenticated_user)
    })
    .bind("0.0.0.0:8081".to_string())?
    .run()
    .await
}
```

**Comment by dermicha** [comment]
THANKS!!

That works for me!!

**Comment by olger** [comment]
Hello @dermicha and @measproem 

I've changed the way to get the config to async. That makes it easier to create a config and there is no need for the spar_blocking anymore. 

It works like:

`let created_validator = OIDCValidator::new_from_issuer(test_issuer.clone()).await.unwrap();
     let validator_config = OIDCValidatorConfig {
         issuer: test_issuer,
         validator: created_validator,
     };`

From 0.5.0 you can do it like this.

**Comment by measproem** [comment]
That awesome thank so much
